#============================================================================================
# Author: Amir ELbasiony
#-------------------------------------------------------------------------------------------
# Usage:
# Run the ansible playbook with the following command:
# ansible-playbook -i inventory --private-key ../todo-app-ssh-key.pem  EC2_server.yaml
#============================================================================================
- hosts: remote_target
  remote_user: "ubuntu"
  become: yes

  roles:
    - docker_install
    # - aws_cli_install
    - K8s_minikube_install
    - argocd_install
    - argocd_apply_app